version: '2'
services:

  mongodb:
    image: mongo:4.2
    hostname: mongodb
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data-mongodb:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: crumbl
      MONGO_INITDB_ROOT_PASSWORD: crumbl
      MONGO_INITDB_DATABASE: crumbl
  
  web:
    build: .
    restart: always
    hostname: signer-api
    container_name: signer-api
    depends_on: 
      - mongodb
    ports:
      - 4000:4000
    environment:
      MONGO_USERNAME: crumbl
      MONGO_PASSWORD: crumbl
      MONGO_DOMAIN: mongodb
      MONGO_PORT: 27017
      MONGO_DB: crumbl
      MONGO_COLLECTION: signer
      BOOTSTRAP_URL: http://localhost:3080/api
      SESSION_SEED: 5ce1dc0cc168ae51410edadad55fdf573ef257c74023f303098393357df8b911 # Change in production
      SIGNER_CODE: defaultSignerCode # Change in production

volumes:
  data-mongodb:
    driver: local
