http:
  port: 4000

mongo:
  username: crumbl
  password: crumbl
  domain: localhost
  port: 27017
  db: crumbl
  collection: signer

bootstrap:
  url: http://localhost:3080/api

signer:
  code: defaultSignerCode # TODO Change in production // TODO Keep it???
